<!-- lib.core -->
<script src="/src/lib/jquery-1.8.3.min.js"></script>
<script src="/src/lib/createjs-2013.12.12.min.js"></script>
<script src="/src/lib/underscore-min.js"></script>

<!-- createjs.plugins -->
<script src="/src/lib/creatjs-plugins/particleEmitterJs-0.5.0.min.js"></script>

<!-- amp -->
<script src="/src/amp/amp.js"></script>
<script src="/src/amp/utilitys/amp.utilitys.js"></script>
<script src="/src/amp/createjs/amp.createjs.js"></script>

<!-- common -->
<script src="/js/common.js"></script>
