<!-- core -->
<script src="/src/jquery-1.8.3.min.js"></script>
<script src="/src/createjs-2013.12.12.min.js"></script>
<script src="/src/underscore-min.js"></script>

<!-- createjs.plugins -->
<script src="/src/creatjs-plugins/particleEmitterJs-0.5.0.min.js"></script>

<!-- amp -->
<script src="/src/amp/uncompressed/amp.core.js"></script>
<script src="/src/amp/uncompressed/amp.createjs.js"></script>

<!-- common -->
<script src="/js/common.js"></script>
