<!-- core -->
<script src="/src/jquery-1.8.3.min.js"></script>
<script src="/src/underscore-min.js"></script>
<script src="/src/hogan-3.0.2.min.js"></script>
<script src="/src/imagesloaded.pkgd.min.js"></script>

<!-- jquery.plugins -->
<script src="/src/jquery-plugins/jquery.easing.1.3.min.js"></script>
<script src="/src/jquery-plugins/jquery.mousewheel.min.js"></script>

<!-- amp -->
<script src="/src/amp/original/amp.core.js"></script>
<script src="/src/amp/original/amp.jquery-plugins.js"></script>
<script src="/src/amp/original/amp.utilitys.js"></script>

<!-- common -->
<script src="/js/common.js"></script>
