<!-- lib.core -->
<script src="/src/lib/jquery-1.8.3.min.js"></script>
<script src="/src/lib/underscore-min.js"></script>
<script src="/src/lib/hogan-3.0.2.min.js"></script>
<script src="/src/lib/imagesloaded.pkgd.min.js"></script>

<script src="/src/lib/hammer.min.js"></script>

<!-- jquery.plugins -->
<script src="/src/lib/jquery-plugins/jquery.easing.1.3.min.js"></script>
<script src="/src/lib/jquery-plugins/jquery.mousewheel.min.js"></script>

<!-- amp -->
<script src="/src/amp/amp.js"></script>
<script src="/src/amp/utilitys/amp.utilitys.js"></script>
<script src="/src/amp/jquery-plugins/amp.jquery.plugins.js"></script>
<script src="/src/amp/jquery/amp.jQuery.js"></script>

<!-- common -->
<script src="/js/common.js"></script>
