<!-- libs -->
<script src="/js/libs/jquery-1.8.3.pack.js"></script>
<script src="/js/libs/utilitys.pack.js"></script>
<!--[if gte IE 9]><!--><script src="/js/libs/createjs/createjs-2014.12.12.min.js"></script><!--<![endif]-->

<!-- amp -->
<script src="/js/amp/jquery.plugins.js"></script>
<script src="/js/amp/amp.core.js"></script>
<script src="/js/amp/amp.jquery.js"></script>
<!-- <script src="/js/amp/amp.createjs.js"></script> -->

<!-- common -->
<script src="/sample/shared/js/common.js"></script>
