<header>
<h1><a href="/">ampJS</a></h1>
<p class="link"><a href="https://bitbucket.org/cutupworks/ampjs" target="_blank">Bitbucket Repository</a></p>

<nav>
<ul>
<li><a href="/">amp</a></li>
<li><a href="/amp.core.ease.html">amp.ease</a></li>
<li><a href="/amp.core.fontResize.html">amp.fontResize</a></li>
<li><a href="/amp.core.Mediator.html">amp.Mediator</a></li>
<!-- <li><a href="/amp.core.Iterator.html">amp.Iterator</a></li> -->
<li><a href="/amp.utilitys.html">utilitys</a></li>
<li><a href="/amp.createjs.html">amp.createjs</a></li>
</ul>
</nav>

<small>Copyright 2014 ampJS</small>
<!-- header // --></header>
