<!-- libs -->
<script src="../src/libs/jquery/jquery-1.8.3.min.js"></script>
<script src="../src/libs/jquery/jquery.plugins.js"></script>
<script src="../src/libs/createjs/createjs-2013.12.12.min.js"></script>
<script src="../src/libs/createjs/createjs.plugins.js"></script>
<script src="../src/libs/utilitys/underscore-min.js"></script>
<script src="../src/libs/utilitys/backbone-min.js"></script>
<script src="../src/libs/utilitys/velocity.min.js"></script>
<script src="../src/libs/utilitys/hogan-3.0.2.min.js"></script>
<script src="../src/libs/utilitys/imagesloaded.pkgd.min.js"></script>


<!-- amp -->
<script src="../src/amp/amp.core.min.js"></script>
<script src="../src/amp/amp.utilitys.min.js"></script>
<!-- <script src="../src/amp/amp.jquery.plugins.js"></script> -->
<!-- <script src="../src/amp/amp.jquery.js"></script> -->
<!-- <script src="../src/amp/amp.createjs.js"></script> -->

<!-- common -->
<!-- <script src="/shared/js/common.js"></script> -->
