<header>
<h1><a href="/sample/">ampJS</a></h1>
<p class="link"><a href="https://bitbucket.org/cutupworks/ampjs" target="_blank">Bitbucket Repository</a></p>

<nav>
<ul>
<li><a href="/sample/">amp</a></li>
<li><a href="/sample/amp.core.ease.html">amp.ease</a></li>
<li><a href="/sample/amp.core.fontResize.html">amp.fontResize</a></li>
<li><a href="/sample/amp.core.Mediator.html">amp.Mediator</a></li>
<!-- <li><a href="/sample/amp.core.Iterator.html">amp.Iterator</a></li> -->
<li><a href="/sample/amp.jquery.html">jquery</a></li>
<li><a href="/sample/amp.createjs.html">createjs</a></li>
</ul>
</nav>

<small>Copyright 2014 ampJS</small>
<!-- header // --></header>
