<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<title>amp.js</title>
<meta name="description" content="amp Javascript Library">
<meta name="keywords" content="amp,js,javascript,library">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no">
<meta name="format-detection" content="telephone=no,address=no,email=no">

<link href="http://fonts.googleapis.com/css?family=Rokkitt:400,700" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="shared/css/global.css" media="all">
<link rel="stylesheet" href="shared/css/common.css" media="all">
