<!-- core -->
<script src="/src/libs/jquery-1.8.3.min.js"></script>
<script src="/src/libs/velocity.min.js"></script>
<script src="/src/libs/underscore-min.js"></script>
<script src="/src/libs/hogan-3.0.2.min.js"></script>
<script src="/src/libs/imagesloaded.pkgd.min.js"></script>

<!-- jquery.plugins -->
<script src="/src/libs/jquery.plugins.js"></script>

<!-- createjs -->
<script src="/src/libs/createjs-2014.12.12.min.js"></script>
<script src="/src/libs/createjs.plugins/particleEmitterJs-0.5.0.min.js"></script>

<!-- amp -->
<script src="/src/amp/jquery.plugins.js"></script>
<script src="/src/amp/amp.core.js"></script>
<script src="/src/amp/amp.utilitys.js"></script>
<!-- <script src="/src/amp/amp.jquery.js"></script> -->
<!-- <script src="/src/amp/amp.createjs.js"></script> -->

<!-- common -->
<script src="/shared/js/common.js"></script>
