<!-- core -->
<script src="/src/jquery-1.8.3.min.js"></script>
<script src="/src/createjs-2013.12.12.min.js"></script>
<script src="/src/hogan-3.0.2.min.js"></script>
<script src="/src/imagesloaded.pkgd.min.js"></script>
<script src="/src/underscore-min.js"></script>

<!-- jquery.plugins -->
<script src="/src/jquery.plugins.js"></script>

<!-- createjs.plugins -->
<script src="/src/createjs.plugins/particleEmitterJs-0.5.0.min.js"></script>

<!-- amp -->
<script src="/src/amp/amp.core.js"></script>
<script src="/src/amp/amp.utilitys.js"></script>
<script src="/src/amp/amp.jquery.plugins.js"></script>
<script src="/src/amp/amp.jquery.js"></script>
<!-- <script src="/src/amp/amp.createjs.js"></script> -->

<!-- common -->
<script src="/shared/js/common.js"></script>
